"""The dependency licence gate (E01-30)."""

import importlib.util
import json
import sys
from email.message import Message
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "tools/dev/check_licences.py"


def _load() -> ModuleType:
    spec = importlib.util.spec_from_file_location("check_licences", SCRIPT)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["check_licences"] = module
    spec.loader.exec_module(module)
    return module


lic = _load()
POLICY = lic.Policy(
    allowed=("MIT", "BSD-3-Clause", "Apache-2.0", "MPL-2.0"),
    review=("LGPL-*", "EPL-*"),
    denied=("GPL-*", "AGPL-*"),
)
BSD = "License :: OSI Approved :: BSD License"
MIT_CLASSIFIER = "License :: OSI Approved :: MIT License"


class FakeDist:
    """An object exposing ``metadata`` and ``version`` like ``importlib.metadata.Distribution``."""

    def __init__(
        self,
        name: str,
        *,
        expression: str | None = None,
        licence: str | None = None,
        classifiers: tuple[str, ...] = (),
        version: str = "1.0",
    ) -> None:
        message = Message()
        message["Name"] = name
        if expression is not None:
            message["License-Expression"] = expression
        if licence is not None:
            message["License"] = licence
        for classifier in classifiers:
            message["Classifier"] = classifier
        self.metadata = message
        self.version = version


@pytest.mark.parametrize(
    ("dist", "expected"),
    [
        (FakeDist("a", expression="Apache-2.0", licence="MIT"), "Apache-2.0"),
        (FakeDist("b", classifiers=(MIT_CLASSIFIER,)), "MIT"),
        (FakeDist("c", licence="MIT License"), "MIT"),
        (FakeDist("d", licence="Apache Software License"), "Apache-2.0"),
        (FakeDist("e", licence="BSD 2-Clause License"), "BSD-2-Clause"),
        (FakeDist("f", licence="PSF"), "PSF-2.0"),
        (FakeDist("g", licence="UNKNOWN", classifiers=(MIT_CLASSIFIER,)), "MIT"),
        (FakeDist("h", licence="Copyright (c) ...\n\nPermission is hereby granted"), "unknown"),
        (FakeDist("i", licence="x" * 101, classifiers=(MIT_CLASSIFIER,)), "MIT"),
        (FakeDist("j", licence="BSD", classifiers=(BSD,)), "BSD-3-Clause"),
        (FakeDist("k", licence="BSD"), "unknown"),
        (FakeDist("l", classifiers=(BSD,)), "unknown"),
        (FakeDist("m"), "unknown"),
    ],
    ids=lambda value: value if isinstance(value, str) else value.metadata["Name"],
)
def test_licence_resolution(dist: FakeDist, expected: str) -> None:
    assert lic.licence_of(dist) == expected


@pytest.mark.parametrize(
    ("expression", "expected"),
    [
        ("MIT", "allowed"),
        ("MIT OR GPL-3.0-only", "allowed"),
        ("MIT AND GPL-3.0-only", "denied"),
        ("Apache-2.0 WITH LLVM-exception", "review"),
        ("(MIT OR GPL-2.0-only) AND (Apache-2.0 OR LGPL-2.1-only)", "allowed"),
        ("((MIT AND LGPL-3.0-only) OR GPL-3.0-only)", "review"),
        ("LGPL-3.0-or-later", "review"),
        ("LGPL-2.1-only", "review"),
        ("GPL-2.0-or-later", "denied"),
        ("AGPL-3.0-only", "denied"),
        ("Proprietary-Thing", "unknown"),
        ("MIT AND", "unknown"),
        ("(MIT", "unknown"),
        ("MIT) OR (Apache-2.0", "unknown"),
        ("OR MIT", "unknown"),
        ("MIT / Apache", "unknown"),
        ("", "unknown"),
    ],
)
def test_expressions(expression: str, expected: str) -> None:
    assert lic.classify("pkg", expression, POLICY) == expected


def test_wildcards() -> None:
    assert lic.classify("p", "LGPL-3.0-or-later", POLICY) == "review"
    assert lic.classify("p", "LGPL-2.1-only", POLICY) == "review"  # GPL-* does not match LGPL
    assert lic.classify("p", "GPL-3.0-only", POLICY) == "denied"


def test_runtime_closure() -> None:
    export = (
        "# This file was autogenerated by uv\n"
        "Alembic==1.20.0\n"
        "    # via codekavach\n"
        "cffi==2.1.1 ; platform_python_implementation != 'PyPy' and sys_platform == 'linux'\n"
        "jaraco.classes==3.4.0\n"
        "Typing_Extensions==4.0 \\\n"
        "pydantic[email]==2.9\n"
        "-e .\n"
        "\x1b[32m# coloured comment\x1b[39m\n"
    )
    assert lic.runtime_closure(export) == {
        "alembic",
        "cffi",
        "jaraco-classes",
        "typing-extensions",
        "pydantic",
    }


@pytest.mark.parametrize(
    ("classification", "runtime_fails", "dev_fails"),
    [
        ("allowed", False, False),
        ("exception", False, False),
        ("review", True, False),
        ("unknown", True, False),
        ("denied", True, True),
    ],
)
def test_scope_rules(classification: str, runtime_fails: bool, dev_fails: bool) -> None:
    assert lic.fails(classification, "runtime") is runtime_fails
    assert lic.fails(classification, "dev") is dev_fails


def write_policy(tmp_path: Path, exceptions: str = "") -> Path:
    path = tmp_path / "pyproject.toml"
    path.write_text(
        "[tool.codekavach.licences]\n"
        'allowed = ["MIT", "Apache-2.0"]\nreview = ["LGPL-*"]\ndenied = ["GPL-*"]\n'
        f"[tool.codekavach.licences.exceptions]\n{exceptions}",
        encoding="utf-8",
    )
    return path


def run(
    tmp_path: Path, dists: list[FakeDist], runtime: list[str], *extra: str, exceptions: str = ""
) -> int:
    export = tmp_path / "export.txt"
    export.write_text("".join(f"{name}==1.0\n" for name in runtime), encoding="utf-8")
    pyproject = write_policy(tmp_path, exceptions)
    args = ["--export", str(export), "--pyproject", str(pyproject), *extra]
    result: int = lic.main(args, distributions=dists)
    return result


def test_end_to_end_clean(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    dists = [FakeDist("good", expression="MIT"), FakeDist("tool", licence="LGPL-3.0-only")]
    assert run(tmp_path, dists, ["good"]) == 0
    assert "tool" not in capsys.readouterr().out
    assert run(tmp_path, dists, ["good"], "--include-dev") == 0
    assert "LGPL-3.0-only" in capsys.readouterr().out


def test_denied_runtime_package_fails_and_is_named(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    dists = [FakeDist("good", expression="MIT"), FakeDist("bad", expression="GPL-3.0-only")]
    assert run(tmp_path, dists, ["good", "bad"]) == 1
    err = capsys.readouterr().err
    assert "bad 1.0 is GPL-3.0-only (denied, runtime)" in err


def test_denied_dev_tool_fails(tmp_path: Path) -> None:
    dists = [FakeDist("tool", expression="GPL-3.0-only")]
    assert run(tmp_path, dists, [], "--include-dev") == 1
    assert run(tmp_path, dists, []) == 0  # not listed without --include-dev


def test_exception_turns_review_into_pass(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    dists = [FakeDist("weak", expression="LGPL-3.0-only")]
    assert run(tmp_path, dists, ["weak"]) == 1
    capsys.readouterr()
    exception = (
        '"Weak" = { licence = "LGPL-3.0-only", reason = "dynamic use", approved_in = "#1" }\n'
    )
    assert run(tmp_path, dists, ["weak"], "--format", "json", exceptions=exception) == 0
    rows = json.loads(capsys.readouterr().out)
    assert rows == [
        {
            "package": "weak",
            "version": "1.0",
            "licence": "LGPL-3.0-only",
            "classification": "exception",
            "scope": "runtime",
        }
    ]


def test_stale_exception_and_platform_packages_warn(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    exception = '"gone" = { licence = "MIT", reason = "r", approved_in = "#1" }\n'
    assert (
        run(tmp_path, [FakeDist("a", expression="MIT")], ["a", "linux-only"], exceptions=exception)
        == 0
    )
    err = capsys.readouterr().err
    assert "stale exception: gone is not installed" in err
    assert "not installed on this platform" in err
    assert "linux-only" in err


def test_repository_policy_and_environment_pass(capsys: pytest.CaptureFixture[str]) -> None:
    policy = lic.Policy.from_pyproject()
    assert "MIT" in policy.allowed
    assert "GPL-*" in policy.denied
    for name, entry in policy.exceptions.items():
        assert entry["licence"] and entry["reason"] and entry["approved_in"], name


def test_json_fields_on_the_real_environment(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    export = tmp_path / "export.txt"
    export.write_text("pydantic==2\n", encoding="utf-8")
    assert lic.main(["--export", str(export), "--format", "json"]) == 0
    rows: list[dict[str, Any]] = json.loads(capsys.readouterr().out)
    assert rows
    assert all(
        set(row) == {"package", "version", "licence", "classification", "scope"} for row in rows
    )
